apiVersion: v1
kind: Service
metadata:
  name: cycling-club-web
  namespace: cycling-club
  labels:
    app: cycling-club-web
spec:
  type: ClusterIP
  selector:
    app: cycling-club-web
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
